version: '3'
services:
  idm-tools:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
     - .:/rails-app
    ports: ['3000:3000','3001:3001']
    expose:
      - "3000"
      - "3001"
    stdin_open: true
    tty: true
    container_name: idm-tools
