version: '3'
volumes:
  tmp:
services:
  webapp:
    build: .
    image: idms-git-registry.oit.duke.edu/da129/openshift-hello-world:2.0
    volumes:
     - .:/application
     - tmp:/tmp
    ports: ['3000:3000','3001:3001']
    expose:
      - "3000"
      - "3001"
    stdin_open: true
    tty: true
    container_name: openshift-hello-world
