version: '3'
services:
  webapp:
    build: .
    volumes:
     - .:/application
    ports: ['3000:3000','3001:3001']
    expose:
      - "3000"
      - "3001"
    stdin_open: true
    tty: true
    container_name: openshift-hello-world
